language: android
sudo: enabled
env:
    - ANDROID_HOME=$HOME/android-sdk
android:
    install:
        # Download and unzip the Android SDK tools (if not already there thanks to the cache mechanism)
        # Latest version available here: https://developer.android.com/studio/#command-tools
        - if test ! -e $HOME/android-sdk-dl/sdk-tools.zip ; then curl https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip > $HOME/android-sdk-dl/sdk-tools.zip ; fi
        - unzip -qq -n $HOME/android-sdk-dl/sdk-tools.zip -d $HOME/android-sdk

        # Install or update Android SDK components (will not do anything if already up to date thanks to the cache mechanism)
        - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'tools' > /dev/null
        - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platform-tools' > /dev/null
        - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'build-tools;27.0.3' > /dev/null
        - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'platforms;android-27' > /dev/null
        - echo y | $HOME/android-sdk/tools/bin/sdkmanager 'extras;google;m2repository' > /dev/null
    components:
        # Specify at least one system image,
        # if you need to run emulator(s) during your tests
        - sys-img-armeabi-v7a-android-28
    licenses:
        - android-sdk-license-.+
        - google-gdk-license-.+    
before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
        - $HOME/.android/build-cache
        - $HOME/android-sdk-dl
        - $HOME/android-sdk
before_install:
  - yes | sdkmanager "platforms;android-28"
  - openssl aes-256-cbc -K $encrypted_b5120e425b3b_key -iv $encrypted_b5120e425b3b_iv -in app/googlejson.enc -out app/google-services.json -d

  - "./gradlew dependencies || true"
  
# Emulator Management: Create, Start and Wait
#before_script:
#  - echo no | android create avd --force -n test -t android-28 --abi armeabi-v7a
#  - emulator -avd test -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &
  
script:
    - "./gradlew clean build --stacktrace"
    - "./gradlew connectedCheck"
